# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_ADMIN_SOPORTE: [ROLE_ADMIN,ROLE_SOPORTE]
        ROLE_ADMIN_SERVICIO: [ROLE_ADMIN,ROLE_SERVICIO]
        ROLE_SUPERADMIN: [ROLE_ADMIN,ROLE_ADMIN_SOPORTE,ROLE_ADMIN_SERVICIO]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /productos
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /login
            anonymous:    true
            fr3d_ldap:  ~
            anonymous:  true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/confirmed, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_SUPERADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_SUPERADMIN }
        #- { path: ^/categoria/, role: ROLE_SOPORTE }
        #- { path: ^/solicitud/, role: [ROLE_SOPORTE,ROLE_USER] }