hap_equipos_homepage:
    path:     /hello/{name}
    defaults: { _controller: HapEquiposBundle:Default:index }
    
_productos:
    resource: "@HapEquiposBundle/Controller/ProductosController.php"
    type:     annotation
    prefix:   /
    
_marca:
    resource: "@HapEquiposBundle/Controller/MarcaController.php"
    type:     annotation
    prefix:   /
    
_inventario:
    resource: "@HapEquiposBundle/Controller/InventarioController.php"
    type:     annotation
    prefix:   /
    
_departamentos:
    resource: "@HapEquiposBundle/Controller/DepartamentosController.php"
    type:     annotation
    prefix:   /

_so:
    resource: "@HapEquiposBundle/Controller/SOController.php"
    type:     annotation
    prefix:   /

_servicios:
    resource: "@HapEquiposBundle/Controller/ServiciosController.php"
    type:     annotation
    prefix:   /
    
_servidores:
    resource: "@HapEquiposBundle/Controller/ServidoresController.php"
    type:     annotation
    prefix:   /
    
_bitacoraCentroDatos:
    resource: "@HapEquiposBundle/Controller/BitacoraCentroDatosController.php"
    type:     annotation
    prefix:   /
