hap_equipos_homepage:
    path:     /hello/{name}
    defaults: { _controller: HapEquiposBundle:Default:index }
    
_equipos:
    resource: "@HapEquiposBundle/Controller/ProductosController.php"
    type:     annotation
    prefix:   /
