<?php

namespace Hap\EquiposBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BitacoraCentroDatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BitacoraCentroDatosRepository extends EntityRepository
{
}
